### ISSUE TITLE
no-irregular-whitespace error on first character of every file

### ISSUE THREAD

**Issue by ChrisMBarr** [vladeck/TSLint#8] opened 2017-10-16 15:54 UTC
I get a violation of the [no-irregular-whitespace](https://palantir.github.io/tslint/rules/no-irregular-whitespace) rule for **every file** I open.  This rule **is enabled** in my `tslint.json` file, but when I run my tslint task via gulp, I do not get a violation for this rule.  I'm not sure what it's reporting here.

![image](https://user-images.githubusercontent.com/463685/31621768-920f1cc0-b268-11e7-8922-0d6b998a3558.png)

![image](https://user-images.githubusercontent.com/463685/31621729-7424613e-b268-11e7-9dc8-e29c6ce013e0.png)

**Comment by vladimir-djokic** [comment] 2017-10-16 22:46
This is caused by **UTF-8 BOM**. Running from `Command Prompt`, using `tslint` **5.7.0** and `TypeScript` **2.5.3** shows this error for all `.ts` files created in **Visual Studio**.

**Comment by vladimir-djokic** [comment] 2017-10-27 10:45
I'll close this as it seems like a valid reporting from `tslint`.

**Closed as completed by vladimir-djokic** 2017-10-27 10:45 UTC

**Comment by ChrisMBarr** [comment] 2017-10-27 11:48
Not in my case.  I Running tslint from the command line **does not** report any violations for this rule, it's only with this extension that I see them, and it's in every single file.

![image](https://user-images.githubusercontent.com/463685/32102598-1481ffd0-baeb-11e7-9b9a-7e7513dcf1c3.png)

**Comment by vladimir-djokic** [comment] 2017-10-27 12:07
Please run `tslint` outside `gulp` (`tslint -c tslint.json file.ts`) on one of the `.ts` files that you are having this problem with and check if you still have no violation reports. Check as well what version of `tslint` and `tsc` you have installed and report me your findings.

**Comment by ChrisMBarr** [comment] 2017-10-27 13:14
Well... ok then, you're right!

![image](https://user-images.githubusercontent.com/463685/32105624-23f1a5ae-baf7-11e7-8ac8-07e4fe4ba4db.png)

So why is this?  Does that mean there's an error with gulp-tslint?

**Comment by vladimir-djokic** [comment] 2017-10-27 13:28
I'm not sure. I myself had several cases where invalidations reported by `tslint` were not reported by `gulp-tslint`. As per docs, `gulp-tslint` should use installed version of `tslint`...

I took a quick look at the `gulp-tslint` issues list and found nothing that resembles the issue you are facing. Best bet is to create minimal project with single `.ts` file created in **Visual Studio** (while checking that `tslint` reports the error correctly and `gulp-tslint` does not) and submit it as issue for `gulp-tslint` project.
