### ISSUE TITLE
typescript intellisense shows errors for files not in my project

### ISSUE THREAD

**Issue by vishnu4** [vladeck/TSLint#10] opened 2018-01-09 15:16 UTC
Was told to bring my issue from here:
https://developercommunity.visualstudio.com/content/problem/174770/typescript-intellisense-shows-errors-for-files-not.html
to this repo.

I'm using Visual studio 2017 latest version, and trying to get tsLint to work correctly. For some reason, i'm getting linting errors (in the visual studio Error List (Build+intellisense)) from all of the files in node_modules and any of my declaration (*.d.ts) files as well. Additionally i'm getting linting errors from the typescript SDK folder too ( C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6) Nothing I do seems to fix the issue. I would like to exclude those files from my errors. Everywhere seems to think this is possible, but most examples i find aren't dealing with visual studio and i'm wondering if there is some other extra setting i'm missing. Below are my associated files. i don't have these same issues when i look at my code using VS code, only in visual studio. 

tslint.json:
```
{
  "extends": [
    "tslint:latest",
    "tslint-config-prettier"
  ]
}
```
tsconfig.json:
```
{
  "compilerOptions": {
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "noEmitHelpers": true,
    "noEmitOnError": true,
    "noImplicitAny": false,
    "allowUnusedLabels": true,
    "target": "es5",
    "sourceMap": true,
    "strictNullChecks": false,
    "removeComments": true,
    "declaration": false,
    "plugins": [ { "name": "tslint-language-service" } ],
    "lib": [
      "dom",
      "es6",
      "scripthost",
      "es5",
      "es2015",
      "es2015.promise"
    ],
    "types": [
      "angular-ui-bootstrap",
      "angular",
      "autolinker",
      "bootbox",
      "bootstrap-notify",
      "bootstrap",
      "cldrjs",
      "dragula",
      "globalize",
      "googlemaps",
      "google.analytics",
      "imagesloaded",
      "jquery.blockui",
      "jquery.bootstrap.wizard",
      "jquery",
      "jqueryui",
      "jquery.validation",
      "jsts",
      "kendo-ui",
      "masonry-layout",
      "qtip2",
      "signalr",
      "urijs",
      "moment"
    ]
  },
  "exclude": [
    "node_modules",
    "bower_components",
    "build"
  ],
  "typeRoots": [
    "node_modules/@types",
    "node_modules/moment"
  ],
  "awesomeTypescriptLoaderOptions": {
    "useBabel": true,
    "useCache": true
  },
  "compileOnSave": true,
  "buildOnSave": true 
}
```

**Comment by vladimir-djokic** [comment] 2018-01-09 22:01
Do you have **TSLint** extension (from this project) installed? What are versions of `tslint` and `tsc` installed by npm/project scripts?

**Comment by vishnu4** [comment] 2018-01-09 22:32
In the visual studio link above, i was directed to come to this site even though i never mentioned using your extension at all.  I wasn't using your extension.  Since then, i have installed the latest version of your extension w/out any changes in my issues   I have the following in my package.json devDependencies:

"tslint": "^5.8.0",
    "tslint-microsoft-contrib": "^5.0.1",
    "tslint-language-service": "^0.9.7",
    "tslint-config-prettier": "^1.6.0",
    "typescript": "^2.6.2",

let me know if you need any more information

**Comment by vladimir-djokic** [comment] 2018-01-10 08:55
I'm unable to reproduce the issue you are facing. Please provide minimal project/configuration that can manifest this problem using this extension. Using other tools/extensions is out of scope for this project.

**Comment by vishnu4** [comment] 2018-01-18 23:19
take a look at https://github.com/vishnu4/TSLintRepo .  it's a teardown of my existing project with almost everything removed.  it won't compile, but you can still easily see when loaded into visual studio you get all sorts of typescript errors that shouldn't be there.  Let me know if you have any issues with it, just remember, the c# is not meant to compile, the site isn't meant to load.  it's just enough to show the issue.  See attached image for what i mean
![capture](https://user-images.githubusercontent.com/1782150/35126591-fc3eb396-fc62-11e7-9209-69b5d6aeaca6.PNG)

**Comment by vladimir-djokic** [comment] 2018-01-21 12:37
That error list is **not** coming from **this** extension. It is from built-in **TypeScript** checking that **Visual Studio** has.

**Closed as completed by vladimir-djokic** 2018-01-21 12:37 UTC
Labels: invalid
